### ISSUE TITLE
Add map product to the layer with their coordinate system

### ISSUE THREAD

**Issue by LNArtus** [earthdaily/qgis-plugin#214]
Currently, when the user wants to add a map product, the layer does not have a coordinate system and must therefore define the desired coordinate system by hand.

**Describe the solution you'd like**
when the user is on the last panel center and when they want to add the product to their project, they should be not add a crs. 
the map should be processed with the Geographic Information System equal to EPSG:4326 - WGS 84 - Géographique

What is currently dev : 
![image](https://user-images.githubusercontent.com/69202500/164502114-de14d654-fcc7-4410-a1da-ad5584edc91d.png)
What is requested : 
![image](https://user-images.githubusercontent.com/69202500/164502856-849f925c-4ec5-4b4e-9f31-e533151e513a.png)

**Comment by vermeulendivan** [comment]
@LNArtus Hi Helene! Noted that tif, shp and kmz has no issue and the coordinate system is correct. This issue is only with png. Also, the coordinate system is not set by the plugin for tif, shp, or kmz - which indicates that the API does this. Is it possible that this should be the same for the png format?
I've also send you an email on this - more detailed.
