### ISSUE TITLE
Missing map types in the drop down list

### ISSUE THREAD

**Issue by vincentlel** [earthdaily/qgis-plugin#39]
In the Map Product Type drop down list, we need to have option for OM, YVM, YGM, ELEVATION, COLOR COMPOSITION, SAMZ. Each of this map type will trigger a call to specific end points.

**Comment by myarjunar** [comment]
could you give me all map product types that will be appeared in the dropdown list?
could you also give me a polygon which has  OM, YVM, YGM, ELEVATION, and SAMZ coverage so I can test the map creation for it? That would really help because so far I only found INSEASON map products from the coverage search. Thanks.

**Comment by myarjunar** [comment]
Based on test dataset, this is the map product that we should include in the map product options:
```
INSEASON_NDVI
INSEASON_GNDVI
INSEASON_EVI
INSEASON_CVI
COLORCOMPOSITION
ELEVATION
YGM
YPM/YVM
OM
SAMZ
DIFFERENCE_MAP
```

please correct me if I'm wrong @VincentLel

**Comment by vincentlel** [comment]
Then the list should contain:
NDVI
INSEASONPARTIAL_NDVI
INSEASONPARTIAL_EVI
INSEASON_LAI
Difference_map is really a difference between 2 NDVI or EVI maps. So this "Difference" options can only be selected once 2 NDVI or EVI maps have been selected. In the initial requirement deck, we suggestion to have a button in the bottom of the coverage panel enabled only when 2 maps have been selected
